### ISSUE TITLE
All TODO in the code should be replaced with Github issues.

### ISSUE THREAD

**Issue by maraca** [at4260/FinancialApp#3]
This is done to give more visibility into features and bugs that need to be resolved.

**Comment by maraca** [comment]
Here is an example https://github.com/at4260/FinancialApp/blob/77de8f08b104602b7479715a2c49325e2244217a/seed_data/data.py#L5

**Comment by at4260** [comment]
[Fixes #3]

**Comment by maraca** [comment]
^ you would have to do this from a commit message ;)

`[Fixes #3]`

**Comment by at4260** [comment]
ah.. thanks! wanted to play around with this- enjoying all the email notifications? haha.

**Comment by maraca** [comment]
Yes! I can even respond to it from my email client :D
